MedicalProgram/apps/doctor/urls.py
from django.urls import path

from . import views


app_name = "doctor"
urlpatterns = [
    path('home/',views.home,name = "home"),
    path('my_cards/',views.my_cards,name="my_cards"),
    path('card/<int:patient_id>/',views.card,name="card"),
    path('add_card_record/<int:patient_id>',views.add_card_record,name="add_card_record"),
    path('add_card_direction/<int:patient_id>',views.add_card_direction,name="add_card_direction"),
    path('add_patient/',views.add_patient,name="add_patient"),
    path('set_patient_dierection/<int:patient_id>/<int:visiting_id>',views.set_patient_dierection,name="set_patient_dierection"),
    path('add_analysis_direction/<int:patient_id>/',views.add_analysis_direction,name="add_analysis_direction"),
    path('set_analysis_direction/<int:patient_id>/<int:visiting_id>/',views.set_analysis_direction,name="set_analysis_direction")

]

MedicalProgram/apps/index/urls.py
from django.urls import path
from . import views
app_name = "index"
urlpatterns = [
    path('',views.home,name="home"),
    path('rating',views.rating,name="rating")

]

MedicalProgram/apps/login/urls.py
from django.urls import path

from . import views


app_name = "login"
urlpatterns = [
    path('',views.login,name = "login"),
    path('logout',views.logout,name="log_out"),
    path('register',views.register,name="register"),
    path('info/',views.info,name="info")
]

MedicalProgram/apps/patient/urls.py
from django.urls import path

from . import views

app_name = "patient"
urlpatterns = [
	path("home/",views.home,name="home"),
	path('my_card/',views.my_card,name="my_card"),
	path('reserve/',views.reserve,name="reserve"),
	path('get_day_visitings/<str:date>/',views.get_day_visiting,name="get_day_visitings"),
	path('set_visiting/<int:visitings_id>/',views.visiting,name="create_visiting"),
	path('vote/',views.vote,name="vote"),


]

MedicalProgram/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('',include('index.urls')),
    path('accounts/',include('login.urls')),
    path('doctor/',include('doctor.urls',namespace="doctor")),
    path('patient/',include('patient.urls',namespace="patient")),
    path('administrator/',include('administrator.urls',namespace="administrator")),   
    path('registry/',include("registry.urls",namespace='registry')),
    path('labolatory-assistant/',include("labolatory-assistant.urls",namespace='labolatory-assistant')),
    path('head-doctor/',include('head-doctor.urls',namespace="head-doctor")),
    path('admin/', admin.site.urls)
]

MedicalProgram/apps/doctor/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/head-doctor/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/index/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/labolatory-assistant/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/login/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/patient/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/registry/models.py
from django.db import models

# Create your models here.

MedicalProgram/apps/doctor/forms.py
from django import forms

from administrator.models import Card

class AddCardRecordForm(forms.Form):
	

	class Meta:
		model = Card
		fields = [
			'content',
			'conclusion'
		]

MedicalProgram/apps/administrator/views.py
from datetime import datetime,timedelta
from django.shortcuts import render,redirect
from django.contrib.postgres.fields import JSONField
from .models import (Doctor
					,Visitings,
					Profession,
					Word,
					Registry,
					AnalysisTemplate,
					LaboratoryAssistant,
					LabolatoryVisitings,
					)
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import auth,User
from django.utils import timezone
from django.contrib import messages
import random



ARRAY = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
 '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-']

def create_pass(lenght):
	return_string = ''
	for i in range(lenght):
		return_string += random.choice(ARRAY)
	return return_string


def home(request):

	doctors = None
	types = Profession.objects.all()
	laborants =None
	if request.method == "POST":

		doctor_name = request.POST['doctor_login']
		doctor_rank = request.POST['doctor_rank']
		doctors = Doctor.objects.filter(name__contains=doctor_name,
									   rank=doctor_rank)


		if doctor_name == "":
			doctors = Doctor.objects.filter(rank=doctor_rank)		
		
		if doctor_rank == "Лаборант":

			laborants = LaboratoryAssistant.objects.filter( 
					name__contains=doctor_name
				)
			print(laborants)

	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_home.html',
											 "menu_render":"administrator/administrator_menu.html",
											 "all_doctors":doctors,
											 "laborants":laborants,
											 "types":types})
def edit_doctor(request,doctor_id):
	doctor = Doctor.objects.get(id=doctor_id)
	types = Profession.objects.filter()	
	if request.method == "POST":
		name = request.POST['name']
		date = datetime(int(request.POST['year']),int(request.POST['month']),int(request.POST['day']))
		rank = request.POST['spec']
		doctor.name = name
		doctor.date_birth = date
		doctor.rank = rank
		doctor.save()
		return HttpResponseRedirect( reverse("administrator:home",args=()) )


	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_edit_doctor.html',
											 "menu_render":"administrator/administrator_menu.html",
											 "doctor":doctor,
											 "types":types})	
def edit_password(request,doctor_id):
	d = Doctor.objects.get(id=doctor_id)
	doctor = User.objects.get(username=d.login)
	if request.method == "POST":
		password1 = request.POST['password']
		password2 = request.POST['password2']
		if password1 == password2:

			doctor.set_password(password1)
			doctor.save()
			return HttpResponseRedirect( reverse("administrator:edit_doctor" , args=(d.id,)) )
	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_edit_password.html',
											 "menu_render":"administrator/administrator_menu.html",
											 "doctor":d,})		


def add_doctor(request):
	ranks = Profession.objects.all()

	if request.method == "POST":
		first_name = request.POST['first_name']
		last_name = request.POST['last_name'] + " " + request.POST['end_name']
		
		password1 = request.POST['password']
		password2 = request.POST['password2']
		rank = request.POST['spec']
	
		try:
			date = datetime(int(request.POST['year']),int(request.POST['month']),int(request.POST['day']))		
		except:
			messages.error(request,"Ви не правильно ввели дату")
		if password1 == password2:
			_type = Profession.objects.get(word=rank)
			if _type.casta == 'doctor':
			
				username = _type.casta + "_%03d" % (User.objects.latest('id').id+1)
				user = User.objects.create_user(username=username,password=password2,first_name=first_name,last_name=last_name)		
				user.save()
				d = Doctor(login=username,name=first_name+last_name,rank=rank,key=create_pass(33),date_birth=date)
				d.save()

				if rank == "Сімейний лікар":
					d.familydoctorvotes_set.create(vote=None)
			elif _type.casta == 'registry':
				username = _type.casta + "_%03d" % (User.objects.latest('id').id+1)
				user = User.objects.create_user(username=username,password=password2,first_name=first_name,last_name=last_name)		
				user.save()
				r  =Registry(login=username,name=request.POST['name'],date_birth=date)
				r.save()
			elif _type.casta == 'labolatory-assistant':
				username = _type.casta + "_%03d" % (User.objects.latest('id').id+1)
				user = User.objects.create_user(username=username,password=password2,first_name=first_name,last_name=last_name)		
				user.save()
				l  = LaboratoryAssistant(login=username,name=request.POST['name'],key=create_pass(10))
				l.save()		
			elif _type.casta == 'head-doctor':
				username = _type.casta + "_%03d" % (User.objects.latest('id').id+1)
				user = User.objects.create_user(username=username,password=password2,first_name=first_name,last_name=last_name)		
			return HttpResponseRedirect( reverse("administrator:add_doctor_information" , args=(user.id,)) )			
		else:
			messages.error(request,"Паролі не збігаються")
		
	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_add_doctor.html',
											"menu_render":"administrator/administrator_menu.html",
											"ranks":ranks
					
										})
def add_doctor_information(request,user_id):
	user = User.objects.get(id=user_id)

	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_add_employee_info.html',
											"menu_render":"administrator/administrator_menu.html",
											"user":user})	



def vocabulary_settings(request):

	words = None
	profession = None
	if request.method == "POST":
		word =request.POST['word']
		profession = Profession.objects.filter(word__contains = word)
		words = Word.objects.filter(word__contains = word)


	
	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_vocabulary_settings.html',
											"menu_render":"administrator/administrator_menu.html",
											"words":words,
											"professions":profession})

def add_word(request):

	if request.method == "POST":
		word1 = request.POST['word1']
		word2 = request.POST['word2']
		code = request.POST['word_code']
		if word1==word2:
			w = Word(word=word1,code = code)
			w.save()
			return HttpResponseRedirect ( reverse("administrator:vocabulary",args=()) )
	 
	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_add_word.html',
											 "menu_render":"administrator/administrator_menu.html",
											})		
def add_profession(request):
	if request.method == "POST":
		profession1 = request.POST['profession1']
		profession2 = request.POST['profession2']
		code = request.POST['profession_code']
		casta = request.POST['cast']
		if profession1==profession1:
			p = Profession(word=profession1,code = code,casta=casta)
			p.save()
			return HttpResponseRedirect( reverse("administrator:vocabulary" ,args=() ) )
	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_add_profession.html',
											 "menu_render":"administrator/administrator_menu.html",
											})			





def schedule(request):

	doctors = None
	laborants = None
	if request.method == "POST":
		name = request.POST['d_name']
		doctors = Doctor.objects.filter(name__contains=name)
		laborants = LaboratoryAssistant.objects.filter(name__contains=name)

  		
	

	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_schedule.html',
											"menu_render":"administrator/administrator_menu.html",
											"doctors":doctors,
											"laborants":laborants
											})

def visiting_template_schedule(request,user):
	type_ = user.split("_")
	if type_[0] == 'doctor':
		employee = Doctor.objects.get(login=user)
	else:
		employee = LaboratoryAssistant.objects.get(login=user)



	hours = [8,9,10,11,12,13,14,15,16,17,18,19,20]
	days = [["1 - й","z1","d1"],
			["2 - й","z2","d2"],
			["3 - й","z3","d3"],
			["4 - й","z4","d4"],
			["5 - й","z5","d5"] ]
	if request.method == "POST":
		data = []
		obj = []
		time_start = request.POST['date'].split(".")
		time_for_one = timedelta(minutes = int( request.POST['time_for'] ) )
		for i in range(len(days)):
			
			hour_start = timedelta(hours = int(request.POST[ days[i][1] ]) )
			
			hour_end = timedelta(hours = int(request.POST[ days[i][2] ]) )

			if hour_end - hour_start != timedelta(hours=0,minutes=0,seconds=0):
				index = (hour_end-hour_start)//timedelta(minutes=15)

				hour_start_add = datetime(int(time_start[2]), int(time_start[1]), int(time_start[0]) )+ timedelta(i)
		
				for e in range(index):
					if type_[0] == 'doctor':
						obj.append(Visitings(
									docotor=employee,
									patient = None,
									date = hour_start_add + hour_start +time_for_one*e
								)								
						)	
					else:
				
						obj.append(LabolatoryVisitings(
									laborant=employee,
									date = hour_start_add + hour_start +time_for_one*e
								)								
						)	
				if type_[0] == 'doctor':			
					Visitings.objects.bulk_create(obj)
				else:
					LabolatoryVisitings.objects.bulk_create(obj)
		return redirect ( "administrator:schedule" )
	return render(request,"cabinet/ok.html",{"main_render":'administrator/administrator_set_schedule.html',
											"menu_render":"administrator/administrator_menu.html",
											"employee":employee,
											"hours":hours,
											"days":days
											})	


################################# ВІДДІЛ АНАЛІЗІВ #######################################################



def analysis_templates(request):
	analysis = AnalysisTemplate.objects.all()
	if request.method == "POST":
		name = request.POST['name']
		rows = request.POST['rows']
		return HttpResponseRedirect( reverse("administrator:create_analysis_templates" , args=(name,rows)) )

MedicalProgram/apps/head-doctor/views.py
from django.shortcuts import render
from administrator.models import Card

def home(request):
    #cards = Card.objects.all().count()
    cards = Card.objects.all().count()
    #print(1)
    return render(request,"cabinet/ok.html",{"main_render":'head-doctor/head-doctor_home.html',
                                            "menu_render":"head-doctor/head-doctor_menu.html",
                                            "count_of_cards":cards})	

MedicalProgram/apps/index/views.py
from django.shortcuts import render
from administrator.models import FamilyDoctorVotes

# Create your views here.

def home(request):
    return render(request,"index/home.html",{})

def rating(request):
    votes = FamilyDoctorVotes.objects.order_by('-vote')
    return render(request,"index/rating.html",{"all_doctors":votes})

MedicalProgram/apps/labolatory-assistant/views.py
from django.shortcuts import render
from django.utils import timezone
from administrator.models import LaboratoryAssistant,LabolatoryVisitings,AnalysisTemplate,Card
from django.http import HttpResponseRedirect
from django.urls import reverse


def home(request):
	l = LaboratoryAssistant.objects.get(login = request.user.username)
	
	v = LabolatoryVisitings.objects.filter(laborant = l,patient__isnull = False)
	viting_now = None
	for i in range(len(v)):
		if v[i].if_in_time():
			viting_now = v[i]

	return render(request,"cabinet/ok.html",{"main_render":'labolatory-assistant/labolatory-assistant_home.html',
											"menu_render":"labolatory-assistant/labolatory-assistant_menu.html",
											"viting_now":viting_now})	

def set_analysis_results(request):
	analysis = LabolatoryVisitings.objects.filter(patient__isnull=False)
	return render(request,"cabinet/ok.html",{"main_render":'labolatory-assistant/labolatory-assistant_set_analysis_results.html',
											"menu_render":"labolatory-assistant/labolatory-assistant_menu.html",
											"analysis":analysis})	

def list_of_analysis(request,visiting_id):
	analysis = LabolatoryVisitings.objects.get(id=visiting_id)	
	if analysis.analys_type == "":
		analysis.delete()
		return HttpResponseRedirect( reverse( "labolatory-assistant:set_analysis_results" ,args =() ) )
	analysis_types = analysis.analys_type.split("|")

	analysis_types2 = []
	for i in range(len(analysis_types)):
		if analysis_types[i] != "":
			analysis_types2.append(analysis_types[i])
	return render(request,"cabinet/ok.html",{"main_render":'labolatory-assistant/labolatory-assistant_list_of_analysis.html',
											"menu_render":"labolatory-assistant/labolatory-assistant_menu.html",
											"analysis":analysis,
											"analysis_types":analysis_types2})		

def set_analys(request,visiting_id,analys):
	analysis = LabolatoryVisitings.objects.get(id=visiting_id)	
	template = AnalysisTemplate.objects.get(name = analys)

	a = template.template.split("|")
	

	return_list = []
	for i in range(len(a)):
		if a[i] != '':
		
			return_list.append(a[i][0:len(a[i])-2])
	if request.method == "POST":
		b = template.template

		for i in return_list:

			
			b = b.replace("#",request.POST[i],1)

		analysis.patient.card_set.create(
								date = timezone.now(),
								content_type = "analysis",
								second_title = template.name,
								content = b,
								conclusion = None
							)

		analysis.analys_type = analysis.analys_type .replace( template.name+"|" , '',1 )


		analysis.save()
		return HttpResponseRedirect( reverse( "labolatory-assistant:list_of_analysis" ,args = (analysis.id,) ) )
	



	return render(request,"cabinet/ok.html",{"main_render":'labolatory-assistant/labolatory-assistant_set_analys.html',
											"menu_render":"labolatory-assistant/labolatory-assistant_menu.html",
											"analysis":analysis,
											"analysis_type":analys,
											"fields":return_list
											})			

MedicalProgram/templates/patient/patiens_get_day_visitings.html
{% block main %}
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Прийоми на {{ date }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
          
          </div>

        </div>
   </div>
   <div class="visitings">
      <div class="row">
   		{% for visiting in visitings %}
        <div class="col-xl-2 col-lg-3 col-md-6 col-sm-12">
    			<div class="card">
    				<div class="card-body">
    					<a href="{% url 'patient:create_visiting' visiting.id %}" class="card-title">{{ visiting.date|date:"H:i" }}</a>


    				</div>


    			</div>
          <br>
        </div>
		  {% endfor %}
    </div>

{% endblock %}

MedicalProgram/templates/patient/patient_home.html
{% block main %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Головна</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
          
          </div>

        </div>
      </div>
	<div class="a">
		<div class="row">
			<div class="col-lg-6 col-md-12">
				<div class="card bg-success">
					<div class="card-header">
						<h2>Наступні відвідини</h2>
					</div>
					<div class="card-body">
						{% if visiting %}
							<h1 class="font-weight-normal">{{ earliest_visiting.docotor.rank }} | {{ earliest_visiting.docotor.name }}</h1>
						{% else %}
							<h1 class="font-weight-normal">Зараз немає відвідування</h1>
						{% endif %}

					</div>
				</div>						
			</div>
			<div class="col-md-6">
				
			</div>			
		</div>
	</div>

	<div class="patients">


		<h1 class="h2">Запланлвані відвідини</h1>

		<table class="table table-bordered">
		  <thead class="table-dark">
		    <tr>
		      <th scope="col">Номер</th>
		      <th scope="col">Лікар</th>
		      <th scope="col">Дата</th>
		    </tr>
		  </thead>
		  <tbody>
				{% for visiting in all_visitings %}
					<tr>
						<th scope="row">{{ visiting.id }}</th>
						<td>{{ visiting.docotor.name }}</td>
						<td>{{ visiting.date|date:"H:i" }}</td>
					</tr>



				{% endfor %}
		  </tbody>
		</table>

	</div>





{% endblock %}

MedicalProgram/templates/patient/patient_menu.html
{% block menu %}
	<li class="nav-item">
	    <a class="nav-link active" href="{% url 'patient:home' %}">
	        <span data-feather="home"></span>
	            Головна <span class="sr-only">(current)</span>
	    </a>
	</li>
	<li class="nav-item">
			<a class="nav-link active" href="{% url 'patient:my_card' %}">
				<span data-feather="home"></span>
					Моя картка <span class="sr-only">(current)</span>
			</a>
		</li>
	<li class="nav-item">
	    <a class="nav-link active" href="{% url 'patient:reserve' %}">
	        <span data-feather="home"></span>
	            Записатись на прийом <span class="sr-only">(current)</span>
	    </a>
	</li>
	<li class="nav-item">
	    <a class="nav-link active" href="{% url 'patient:vote' %}">
	        <span data-feather="home"></span>
	           	Оцінка сімейного лікаря<span class="sr-only">(current)</span>
	    </a>
	</li>




{% endblock %}

MedicalProgram/templates/patient/patient_my_card.html
{% block main %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Картка {{ patient.name }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">

          </div>

        </div>
      </div>
     <div class="search">
     	<form action="{% url 'patient:my_card' %}" method="POST">
      		{% csrf_token %}
     		<div class="row">
     			<div class="col-lg-8 col-md-12 p_input">
     				<input type="text" placeholder="ДД.ММ.РР" class="form-control" name="date" />

					 </div>
					 <div class="col-lg-2 col-md-12 p_input">
							<select class="selectpicker form-control" data-style="btn-primary" data-live-search="true" name="doctor_rank">
								{% for type in types %}
										<option value="{{ type.word }}">{{ type.word }}</option>
								{% endfor %}
							</select>						 
					 </div>
					<div class="col-lg-2 col-md-12 p_input">
						<button class="btn btn-info btn-block" type="submit">Шукати</button>
					</div>
     		</div>

     	</form>
     	<br>
     </div>
	{% if carsd_all %}
		{% for c in carsd_all %}
			<div class="card">
				<div class="card-header">
					<h1 class="h2">{{ c.date|date:"d.m.Y H:i" }}</h1>

				</div>
				<div class="card_body" style="padding: 10px;" >
					{% if c.content_type == 'analysis' %}
								<h3 class="font-weight-nprmal">Результати аналізу {{ c.second_title }}</h3>
								<table class="table">
								  <thead>
								    <tr>
								      <th scope="col">Ключ</th>
								      <th scope="col">Значення</th>

								    </tr>
								  </thead>
								  <tbody>
									{% for row in c.analysis_split %}
									    <tr>
									      <th scope="row">{{ row.0 }}</th>
									      <td>{{ row.1 }}</td>

									    </tr>
									{% endfor %}
								  </tbody>
								</table>
					
						{% else %}
							<div class="row">
								<div class="col-md-2">
									<strong>
										Протокол
									</strong>
								</div>
								<div class="col-md-10">
									<p>{{ c.content }}</p>							
								</div>
								{% if c.conclusion %}
									<div class="col-md-2">
										<strong>
											{{ c.second_title }}
										</strong>
									</div>
									<div class="col-md-10">
										<p>{{ c.conclusion }}</p>							
									</div>	
								{% endif %}													
							</div>

							
						{% endif %}					
					

				</div>
			</div>
			<br>
		{% endfor %}
	{% else %}
		<h1 class="f">В картці немає записів</h1>
	{% endif %}

		
{% endblock %}

MedicalProgram/templates/patient/patient_reserve.html
{% block main %}
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Зареєструватись на прийом</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
          
          </div>

        </div>
      </div>

	<br>	
	<div class="row">
		{% for day in days %}
			
			<div class="col-xl-2 col-lg-3 col-md-6 col-sm-12">
				<div class="card">
					<div class="card-body">
						<a href="{% url 'patient:get_day_visitings' day.1 %}" class="card-title">{{ day.0|date:"D d M Y" }}</a>
					</div>
				</div>
				<br>
			</div>


		{% endfor %}
	</div>

{% endblock %}

MedicalProgram/templates/patient/patients_vote.html
{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Оцінити свого сімейного лікаря</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
      
      </div>

    </div>
    </div>
    <br>	
    <form action="{% url 'patient:vote' %}" method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                  <h3 class="font-weight-normal vote_1_pointer_show" style="cursor: pointer;">1.Якість Обслуговування</h3>
                  <h3 class="font-weight-normal vote_1_pointer_hide" style="cursor: pointer;">1.Якість Обслуговування</h3>
                  <div class="vote_1_content">
                        {% for i in balls %}
                           {% if patient.vote == i %}
                               <div class="radio">
                                   <label><input type="radio" name="vote1" value="{{ i }}" checked>{{ i }}</label>
                               </div>
                           {% else %}
                               <div class="radio">
                                   <label><input type="radio" name="vote1" value="{{ i }}">{{ i }}</label>
                               </div>            
                           {% endif %}
                   
                       {% endfor %}
    
                   </div>
            </div>   
        </div>
        <br>
        <div class="card">
                <div class="card-body">
                      <h3 class="font-weight-normal vote_2_pointer_show" style="cursor: pointer;">2.Якість лікування</h3>
                      <h3 class="font-weight-normal vote_2_pointer_hide" style="cursor: pointer;">2.Якість лікування</h3>
                      <div class="vote_2_content">
                            {% for i in balls %}
                               {% if patient.vote == i %}
                                   <div class="radio">
                                       <label><input type="radio" name="vote2" value="{{ i }}" checked>{{ i }}</label>
                                   </div>
                               {% else %}
                                   <div class="radio">
                                       <label><input type="radio" name="vote2" value="{{ i }}">{{ i }}</label>
                                   </div>            
                               {% endif %}
                       
                           {% endfor %}
        
                       </div>
                </div>   
        </div>
        <br>
        {% if patient.can_vote %}
            <button class="btn btn-info" type="submit">Проголосувати</button>
        {% else %}
            <div class="alert alert-danger">Ви вичерпали свій ліміт голосування</div>
        {% endif %}
    </form>


        
        




<script type="text/javascript">

    $( document ).ready(function() {
        $(".vote_1_content").hide();
        $('.vote_1_pointer_hide').hide();
        $(".vote_1_pointer_show").on("click",function(){

            $(".vote_1_content").show(600);
            $('.vote_1_pointer_show').hide();            
            $('.vote_1_pointer_hide').show();

        });
        $('.vote_1_pointer_hide').on("click",function(){
            $(".vote_1_content").hide(600);
            $('.vote_1_pointer_show').show();
            $('.vote_1_pointer_hide').hide();         
        });

        $(".vote_2_content").hide();
        $('.vote_2_pointer_hide').hide();
        $(".vote_2_pointer_show").on("click",function(){

            $(".vote_2_content").show(600);
            $('.vote_2_pointer_show').hide();            
            $('.vote_2_pointer_hide').show();

        });
        $('.vote_2_pointer_hide').on("click",function(){
            $(".vote_2_content").hide(600);
            $('.vote_2_pointer_show').show();
            $('.vote_2_pointer_hide').hide();         
        });
    });

</script>




{% endblock %}